language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: code2bits-github
    token:
      secure: qoDtEjbzqSOmBrbNxhaFJTfEs1CmQCryc+2ODCAhTKTluHP4AV1k3QIR+bDi7T7yIkCa5NZWBhNrJOTrMou2eBBXPSXpu7VYpyJOK/L+TC+U1yGEkI1J/PE2Ychsyv/vzt2gDVBpATX8B0wpwjT7iYRllqHvBYqxfZeS/+Hm76woMb3LlU2L6wvbo8U843abt9BYwPxXBD11/4Opz1MBtkGoLHJX5eAhr6OAcSlP2O9NEYb+0pEe9/+c92KQIUV5ZAFmgE77PbdC/cDtflRaoL7uETSSH+2BQgOxM1v312ToqFsuBoO3+voJNCaXlGBWtVpTR74j8Zf0YGDO05P1QHTlE2alcswz3e/1YZVqlrH0v+yGEUTU9RrvwVuVhMhd9Fq0zh8VQbPBbE1EEBCdwGMTIWwZhrVEbZYougmV2QXPM/gD2WgFP5mC6rg93ZT1nq5RtxzDl/mCHwqHVVRdsQayfIgQXepQWgoyuX7cXSHQ/xhy7MWdNtzxDCftR/wlYwHYfNdP0a5xfMxZA3HpfwtukeDL/nF0ivu3H8MarntKRSVZqZHEtk1OCVuRqNx5rfJHTRUHBxpcnbZYaa939Lt42Uh4xhO9atXwnnqlDDQlFFYMYwGouCsz+dm2jETNQIJ1CwZu3QzcAMotGMaXn7EfRdv8np4Iz5AsheypeGU=
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
env:
  global:
  - secure: BTpyQwSQ3KcqsYklwBQGGAGqb6TW6GShD2IlY+cWqGN6V2pwwnw5v3fhAoEaKq5ntKRKk0cQ8UwYslQE0S1E035jo8Hz82eIH2j7NW2T3tjTTSk9gAc4fVZ++c8QnDFuCT0MlUAWjEc1jYQesm7UC2l2gbpEcmetXvKz+5n8o77HVi9vW/qvRHggf5j46pnh8f2oWqQ6rKAmOHOgOt6WEgS6habchl+IXV4PMYMGqOX7ozhTh/MEWRPUdt4oMu7l6E7A/rflBS86E0ilUt4qSruApcRfvJ7CO/+iAWeN0SyrLXWi6JwA+QjrLoqmV9Mg6Ul0vCJEaKOEWFdmZIBrq8iFPyRxTRGQ1/S1unDcNPxYUrn577VZj+inUryCynjDxzh84xKOesI0q0DGWT1Fe2tAciAEPjUG32eYljBjMknhW530bP7o3mCMAgGaSE2xHz9G1wMbbKhmzD/7lSFd7dkfaS//q8KxefveAFbzvo6z+gsT7HWazf4bp9MF5QlK0+laLVBOC8xGVxGtRDAtqPVzqbfFNhX10BArojHA6d5tVIA2aVVBs1mIl+kUf0xfktVg+CS1+bcQFf3WVsnqRr+JdcubJ/Z2bBTykJVbKPLx6YmT8jUXsL0aDUz5bp4kYJx7knSwJ5tHdbC83ALRwA0KP0CpOyg6u5R3FWykH4c=
  - secure: PpoUeZZZsRq4kec7Z7hFenj7BNH4I0FGDYNm0CkFQ/t/R663zxsYd9sOkU+4ZYZdZ1KsZmxKXDljkIHkJG5H4nRga6Y+0DKB21wlXJoJXb3E/uIzTCB4tTyqFvEtpPxVZS60OTvWIaT3XmVXfnbZFSfRHrPsvotcGpaSQtlcg9uaVKidapd0jqaUukEI+XLIbTGnv9fNqOdkGpOPo48YyMwgHV8Q9Cg4cz0gqkrYhpTaMNYN4k+olUtrU4sgUQX8e8HKJBOu0Rak5UUYoKn5sgshsDv5hYGamYPXjt+oMgsGCT8gl+HSHCx7kIMOL22Fp3BKfWFmnrN+TAOAFT2zsSS6jXi3KSkMt+bKLL0JdqekSlCFjS7LiaBVH4dQxlKojXTUJ5As/hWNxqhkAAttKeJmYcEk4HDEuTVu3v3Qza6lQLY96U2zjzE1Wjf3VoWSilEq+fnDM7TEtN3+GSYmgZWje0ekOuHpxWB9zWMsq3UTlI+ZS/iX1bQPNo/r7pdVD98ydMGcO1yg5TWKPti3MYstteDiDSBqpizW5TqnDmPS2mhB2UiDpZqhP/tKEI2R74k8dB4zGM9UridBrUpjLIYgz1HYVLoz534BcZeti5LZpnW6BPBX7SwWf/1Zrq+iMtWK5T3gTuCdq+pXTy8K/mIxvIE7sr9D7drV+qZ672g=
