language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: code2bits-github
    token:
      secure: "G/1YqOEuXZGJzIJggoy6fCLS1qbwiilR3XEYehFjV+WOCzBEtZU73B0ExI/C8oVNnOG7IxCFuWVER8IleU8JL6bJyuTCTsLGwvYqc3gcCP3dMJf7OKWUvZj/tTa2WfZdYyv79Ycu9K94r9/txH1jSKbCIajy5OXrWj0hV6uxHQ/sqoakI+2ByvCZgbStUGvZ4Et7DqdtUU1dGIui8KBTB33+ClH+ucmXYNfJnbmv2oP+X8np+sWwaEis44mT/JVhmShbWl1MuCNOZcJAy4hpZoUyHNLItSwMqTcZMQ/9kqS3DikSzza5j7Lp8CnmJjbcawXKDMDd80yY3LkwnMXopgzhUGE/SZ+Dv7i1P1mYA8pIYCOMg9fdrzrrq2bCyClMftYihhUmmPBlFhh+lcg27JTA1t9f0OKN32bg5FdGS4QFYCaeoqP42H1CnkZqAmjHtV/w3dPSXaqxa8ztis7m/x7RA1m8rt3hyHFHs/lmX1E/ynrrCzmVIwtCqzhI/+qiL90CeYp22sASBqtA9leZ/20uEdC+rMoJ+S49WZ7FI04NNv4YWggjBJju4npm8Vi6ZtagV1OCvZ2orFjpP6EiadGZxStJIf0homgnLr6mWVqT5m3zjoBmoEgGEic60VvGOyDFrnUJ6BcjvboUXxwAAXaKhIzIIKJMj3bFN5JYfU4="
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
env:
  global:
  - secure: BTpyQwSQ3KcqsYklwBQGGAGqb6TW6GShD2IlY+cWqGN6V2pwwnw5v3fhAoEaKq5ntKRKk0cQ8UwYslQE0S1E035jo8Hz82eIH2j7NW2T3tjTTSk9gAc4fVZ++c8QnDFuCT0MlUAWjEc1jYQesm7UC2l2gbpEcmetXvKz+5n8o77HVi9vW/qvRHggf5j46pnh8f2oWqQ6rKAmOHOgOt6WEgS6habchl+IXV4PMYMGqOX7ozhTh/MEWRPUdt4oMu7l6E7A/rflBS86E0ilUt4qSruApcRfvJ7CO/+iAWeN0SyrLXWi6JwA+QjrLoqmV9Mg6Ul0vCJEaKOEWFdmZIBrq8iFPyRxTRGQ1/S1unDcNPxYUrn577VZj+inUryCynjDxzh84xKOesI0q0DGWT1Fe2tAciAEPjUG32eYljBjMknhW530bP7o3mCMAgGaSE2xHz9G1wMbbKhmzD/7lSFd7dkfaS//q8KxefveAFbzvo6z+gsT7HWazf4bp9MF5QlK0+laLVBOC8xGVxGtRDAtqPVzqbfFNhX10BArojHA6d5tVIA2aVVBs1mIl+kUf0xfktVg+CS1+bcQFf3WVsnqRr+JdcubJ/Z2bBTykJVbKPLx6YmT8jUXsL0aDUz5bp4kYJx7knSwJ5tHdbC83ALRwA0KP0CpOyg6u5R3FWykH4c=
  - secure: PpoUeZZZsRq4kec7Z7hFenj7BNH4I0FGDYNm0CkFQ/t/R663zxsYd9sOkU+4ZYZdZ1KsZmxKXDljkIHkJG5H4nRga6Y+0DKB21wlXJoJXb3E/uIzTCB4tTyqFvEtpPxVZS60OTvWIaT3XmVXfnbZFSfRHrPsvotcGpaSQtlcg9uaVKidapd0jqaUukEI+XLIbTGnv9fNqOdkGpOPo48YyMwgHV8Q9Cg4cz0gqkrYhpTaMNYN4k+olUtrU4sgUQX8e8HKJBOu0Rak5UUYoKn5sgshsDv5hYGamYPXjt+oMgsGCT8gl+HSHCx7kIMOL22Fp3BKfWFmnrN+TAOAFT2zsSS6jXi3KSkMt+bKLL0JdqekSlCFjS7LiaBVH4dQxlKojXTUJ5As/hWNxqhkAAttKeJmYcEk4HDEuTVu3v3Qza6lQLY96U2zjzE1Wjf3VoWSilEq+fnDM7TEtN3+GSYmgZWje0ekOuHpxWB9zWMsq3UTlI+ZS/iX1bQPNo/r7pdVD98ydMGcO1yg5TWKPti3MYstteDiDSBqpizW5TqnDmPS2mhB2UiDpZqhP/tKEI2R74k8dB4zGM9UridBrUpjLIYgz1HYVLoz534BcZeti5LZpnW6BPBX7SwWf/1Zrq+iMtWK5T3gTuCdq+pXTy8K/mIxvIE7sr9D7drV+qZ672g=
